import type {Metadata} from "next";

import "./globals.css";

import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import {Container, CssBaseline, ThemeProvider} from "@mui/material";
import darkTheme from "@/app/dark.theme";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <AppRouterCacheProvider>
            <ThemeProvider theme={darkTheme}>
                <CssBaseline/>
                <Container maxWidth="md">
                    {children}
                </Container>
            </ThemeProvider>
        </AppRouterCacheProvider>
        </body>
        </html>
    );
}
