import type {Metadata} from "next";

import "./globals.css";

import {Container} from "@mui/material";
import ClientProvidersLayout from "@/components/ClientProvidersLayout";
import Header from "@/components/header/Header";
import React, {ReactNode} from "react";
import logout from "@/api/logout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
        {/* remove after development, it caused hydration issue by Grammarly extension*/}
        <body {...(process.env.NODE_ENV === 'development' ? { suppressHydrationWarning: true } : {})}>
        <ClientProvidersLayout>
            <Header logout={logout}/>
            <Container maxWidth="md">
                {children}
            </Container>
        </ClientProvidersLayout>
        </body>
        </html>
    );
}
