import type { Metadata } from 'next';

import './globals.css';

import { Container } from '@mui/material';
import ClientProvidersLayout from '@/components/ClientProvidersLayout';
import Header from '@/components/header/Header';
import React, { ReactNode } from 'react';
import logout from '@/api/logout';
import authenticated from '@/api/authenticated';

export const metadata: Metadata = {
  title: 'Shoppy App',
  description: 'Generated by create Next app and Nest'
};

export default async function RootLayout({
 children
}: Readonly<{
  children: ReactNode;
}>) {
  const isAuthenticated = await authenticated();

  return (
    <html lang="en">
    {/* remove after development, it caused hydration issue by Grammarly extension*/}
    <body {...(process.env.NODE_ENV === 'development' ? { suppressHydrationWarning: true } : {})}>
    <ClientProvidersLayout>
      <Header logout={logout} />
      <Container className={isAuthenticated ? 'pt-10' : ''}>
        {children}
      </Container>
    </ClientProvidersLayout>
    </body>
    </html>
  );
}
